version: '3.8'

services:
  app:
    build:
      context: ./node-app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db # Node.js  დამოკიდებულია MongoDB სერვისზე და ის პირველად უნდა გაეშვას

  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db #გამოიყენება MongoDB-ის მონაცემების მუდმივად შესანახად

volumes:
  mongo-data: #  MongoDB-ის მონაცემების დასაცავად და შენარჩუნებისთვის
